### ISSUE TITLE
directional.BrightnessT with Stefan-Boltzman's equation

### ISSUE THREAD

**Issue by marinebouchet** [Christiaanvandertol/SCOPE#15]
Dear Prof. van der Tol,   

The calculation of the brightness temperature for each direction is always the same with Stefan-Boltzman's equation :

- calc_brdf l52
```directional.BrightnessT(j) = (pi*rad.Lot/constants.sigmaSB)^0.25;```
=> ```directional.BrightnessT(j) = (pi*directional_rad.Lot/constants.sigmaSB)^0.25;```

In addition, the value of ```directional_rad``` for the specific tto/phi 
of options.m is not the same for ```directional_rad.Lot``` for the same tto/phi...

Many thanks!

Best regards,
Marine Bouchet from CESBIO, Toulouse, France

**Comment by Christiaanvandertol** [comment]
Dear Marine,
Thanks for pointing this out.
You are right about the first point: 'rad' should be 'directional_rad'.

In the previous lines, there are also two mistakes that explain the difference between rad.Lot and directional.Lot for the same geometry: 
The argument of RTMt_sb in Line 50 should contain: .....thermal.Ts(2),thermal.Ts(1),...., instead of ....thermal.Ts(1),thermal.Ts(1).
Second, Line 51 should say:    
        directional.Lot(j)              = directional_rad.Lot; instead of 'directional.Eoutte'

This will give you the correct directional thermal radiance. Apologies for these mistakes! 

You will still notice a minimal difference between rad.Lot and directional.Lot of about 0.01 W m-2 sr-1. This is not due to a mistake, but it is because in the energy balance closure iteration loop, the temperatures are updated after RTMt_sb is executed. This update is very small in the last iteration, but it is still there. For this reason, the input temperatures that are used in calc_brdf differ slightly from those used in the last call of RTMb_sb in ebal.

**Comment by sambugu** [comment]
Hello Dr. CvT,

Thanks for pointing this out. The same applies when calling the Planck function in Line45: Tsu and Tsh...and maybe a line for the option's TB as well.

Kr,
sam
