### ISSUE TITLE
Net radiation calculation (thermal)

### ISSUE THREAD

**Issue by marinebouchet** [Christiaanvandertol/SCOPE#17]
Dear Prof. van der Tol,

After ebal function in SCOPE.m l370, every thermal net radiations < 0
``` 
Rnuct: [13x36x60 double] with all values < 0
Rnhct: [60x1 double] with all values < 0
Rnust: -117.2947
Rnhst: -16.8301
 ```
Cause, in RTMt_sb l196,  ``` Emin + Eplu+1 < (2*)radiance ```  by the component

I saw that the while part to construct F1 and F2 at RTMt_sb l160 had a mistake because CONT is always == FALSE since the first iteration :
``` 
cont = abs(F1topn - F1top) > crit;
	with F1topn = -rinf*F2(1) = -rinf * 0 = 0
	and F1top = 0
cont = abs(0 - 0) > crit = false 
``` 
	 
I maybe wrong (i am not an expert at all), but it is strange that Emin starts with something ~2 at the top to something > 400 at the soil whereas Eplu just dropped from 437 (at the bottom) to 433 (at the top)

I don't understand this part. Could you explain what please ?

Many thanks!

Best regards,
Marine Bouchet from CESBIO, Toulouse, France

**Comment by Christiaanvandertol** [comment]
Dear Marine,
Thanks for raising these points.

Indeed net thermal radiation is negative. The vegetation usually emits more thermal radiation than it receives.

SCOPE simulates the radiative transfer of the thermal radiation emitted by the vegetation and soil in RTMt_sb. There is also a component of thermal radiation that is emitted by the atmosphere. The radiative transfer of this atmospheric contribution is not calculated in RTMt_sb, but in RTMo. This explains the vertical profiles in RTMt_sb that you describe. They only include the fluxes originating from soil and vegetation. At the top, Emin is small because it is only the Eplu at the top times the spherical albedo of the atmosphere (which is small). The thermal radiation originating from the atmosphere has an opposite pattern: high Emin at the top and low Emin at the bottom. Of course, measurements of thermal radiation are the sum of the contributions from the atmosphere, soil and vegetation.

The loop is needed because the incoming flux at the top (which is the emitted radiation times the spherical albedo of the atmosphere) is unknown a priori. The question is why the iteration loops is left already after one iteration. This is indeed a coding mistake: One declaration is misplaced and should be placed further down.The loop should be (changes in bold): 
'while cont
    **F1(1)   = F1top;**
    for j   = 1:nl
        F1(j+1) = F1(j)*(1-m*iLAI)+ fHc*Hc(j);
    end
    F2(nl+1) = fbottom*F1(nl+1) + fHs*Hs;
    for j   = nl : -1 : 1
        F2(j)   = F2(j+1)*(1-m*iLAI) + fHc*Hc(j);
    end
    **F1topn  = -rinf*F2(1);**
    cont    = abs(F1topn-F1top)>crit;
    F1top   = F1topn;
    counter = counter + 1;
end'

Usually two iterations suffice and the difference between the first and the second iteration is less than 1 Wm-2. This is a real coding bug, but luckily the effect on the model output is very minor and below the tolerance of the energy balance error. I will correct it here and in RTMt_planck.
